/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 PurpleDonut.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PurpleDonut.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.674, 0.331, 2.797]} scale={5}>
        <mesh geometry={nodes.Purple_Donut001_1.geometry} material={materials.Dough} />
        <mesh geometry={nodes.Purple_Donut001_2.geometry} material={materials['Purple Frosting']} />
        <mesh geometry={nodes.Purple_Donut001_3.geometry} material={materials['Purple Icing']} />
      </group>
    </group>
  )
}

useGLTF.preload('/PurpleDonut.glb')
