/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 YellowDonut.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/YellowDonut.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.689, 0.354, 4.391]} rotation={[3.112, 0.78, 3.137]} scale={5}>
        <mesh geometry={nodes.Yellow_Donut001_1.geometry} material={materials.Dough} />
        <mesh geometry={nodes.Yellow_Donut001_2.geometry} material={materials['Yellow Frosting']} />
        <mesh geometry={nodes.Yellow_Donut001_3.geometry} material={materials['Orange Icing']} />
        <mesh geometry={nodes.Yellow_Donut001_4.geometry} material={materials['Tulip Petals']} />
        <mesh geometry={nodes.Yellow_Donut001_5.geometry} material={materials['Tulip Center']} />
      </group>
    </group>
  )
}

useGLTF.preload('/YellowDonut.glb')
